### ISSUE TITLE
should we add -fopenmp to  default behavior for hipfc ?

### ISSUE THREAD

**Issue by gregrodgers** [ROCmSoftwarePlatform/hipfort#11]
I expect that OpenMP will be used on the CPU to manage multiple tasks to coordinate asynchronous HIP data transfers and kernel launching, especially for multiple devices.   Should we default hipfc behavior with -fopenmp?

**Comment by pbauman** [comment]
IMO no. `hipfort` has nothing to do with OpenMP. It should only manage things that are relevant to it, not extend beyond those boundaries. Otherwise you're then stepping on the toes of other packages.

**Comment by schoonovernumerics** [comment]
I agree with @pbauman , we should allow developers to pass the OpenMP flags when needed, should they choose a hybrid programming model. Additionally, the openmp flags are different across fortran compilers as well, e.g -omp for PGI compilers.

**Comment by gregrodgers** [comment]
makes sense not to set this flag.
