### ISSUE TITLE
vecadd example does not compile : Ubuntu 18.04, GCC 7.4.0

### ISSUE THREAD

**Issue by schoonovernumerics** [ROCmSoftwarePlatform/hipfort#12]
I've installed rocm-dev and hipfort on an Ubuntu 18.04 system with gcc (and gfortran) 7.4.0. After a successful install, I navigate to the `test/vecadd` demo and run
```
hipfc -v hip_implementation.cpp main.f03
```
and the following error message is thrown 
```
export HIP_PLATFORM=hcc DEVICE_LIB_PATH=/opt/rocm/lib HIP_CLANG_PATH=/opt/rocm/llvm/bin

/opt/rocm/bin/hipcc -fno-gpu-rdc -fPIC --offload-arch=gfx900 -c  hip_implementation.cpp  -o /tmp/hipfc-tmp-20135/hipcc.o
clang-10: error: unsupported option '--offload-arch=gfx900'
ERROR:  The following command failed with return code 1.
        /opt/rocm/bin/hipcc -fno-gpu-rdc -fPIC --offload-arch=gfx900 -c  hip_implementation.cpp  -o /tmp/hipfc-tmp-20135/hipcc.o
```

**Comment by schoonovernumerics** [comment]
This may also be related to #13 where ROCm 3.3.0 is currently in use on the system that causes this error. However, until upstream the deb repository issue with rocm-dkms3.5.0 is resolved, this issue is stuck.

**Comment by gregrodgers** [comment]
Yeah, lets add some smarts to hipfc to check for ROCm version when we have amdgcn target.   We need ROCm 3.5.   This was the first release of ROCm that makes the hip runtime a single runtime without HCC runtimes.

**Comment by schoonovernumerics** [comment]
This looks good with the latest master commit. Closing!
