### ISSUE TITLE
Preserve ordering of arguments to hipfc

### ISSUE THREAD

**Issue by schoonovernumerics** [ROCmSoftwarePlatform/hipfort#14]
When porting an application over to hipfort (from hip-fortran), I noticed that hipfc will switch the order of the arguments internally by the time the calls are made to `$HIPFORT_COMPILER`.

This has caused problems for an application build that depends on additional 3rd party libraries. For example, during a linking stage of a program, I call
```
FFLAGS=-O0 -g -DGPU -ffree-line-length-none -I/usr/local/jsonfortran-gnu-7.1.0/lib
FLIBS=-L/usr/local/jsonfortran-gnu-7.1.0/lib -ljsonfortran
hipfc ${FFLAGS} *.o  ${FLIBS} -o $@
```
This stage of my builds fail with "undefined reference errors" related to json-fortran (3rd party library). The command issued within hipfc that causes the failure is
```
ERROR:  The following command failed with return code 1.
        /usr/bin/gfortran  -g -cpp -I/opt/rocm/hipfort/include/nvptx  -L/usr/local/jsonfortran-gnu-7.1.0/lib -ljsonfortran -DGPU -ffree-line-length-none -I/usr/local/jsonfortran-gnu-7.1.0/lib  CommonRoutines.o ConstantsDictionary.o EquationParser_Class.o Lagrange_Class.o Lagrange_Class_Tests.o Lagrange_HIP.o Lagrange_Test.o ModelPrecision.o Quadrature.o -L/usr/local/cuda/targets/x86_64-linux/lib -lcudart -lstdc++ -L/opt/rocm/hipfort/lib -lhipfort-nvptx -o /home/joeschoonover/apps/fluids/self-fluids/src/self/test
```
Notice that ` -L/usr/local/jsonfortran-gnu-7.1.0/lib -ljsonfortran` is currently placed before the .o files - this causes the undefined reference error (order matters here). Manually copying this command and placing the linker flags for json fortran after the .o results in a successful build.

**Comment by schoonovernumerics** [comment]
On a related note, I'm finding that hipfc does not pass optimization flags to hipcc when .c and .cpp files are encountered. 

As an example, when testing code on Nvidia hardware, I typically pass the `--fmad=false` flag to disable fused multiply-add so that I can compare results between CPU and GPU kernels. hipfc, in its current state does not pass flags like this to hipcc.

**Comment by gregrodgers** [comment]
Yeah, I found a bug and pushed a fix where hipfc was not passing through -lrocfft and other library flags.  This script needs a lot of work.  Your fix for arg ordering is welcome.

**Comment by schoonovernumerics** [comment]
Closing this issue. Latest master branch has this issue resolved.
