### ISSUE TITLE
Should we start all module names with hipfort?

### ISSUE THREAD

**Issue by gregrodgers** [ROCmSoftwarePlatform/hipfort#22]
Currently the hip module requires "use hip" .  The other modules have names such as rocfft etc.    I propose that we establish a convention where all hipfort modules begin with hipfort for three reasons.  1.  The current names may conflict with existing user module names.  2. It will be clear in the source code when an application is using hipfort modules.  3. Builds some brand recognition around hipfort. 

use hip --> use hipfort
use rocfft --> use hipfort_rocfft
use hipblas -> use hipfort_hipblas  or use hipfort_blas if we can get a single blas interface for nvptx and amdgcn

This is the time to do this before hipfort gets too popular and changing this would be impossible with existing applications.

**Comment by schoonovernumerics** [comment]
I am in favor of switching to hipfort prefixes so that there is consistency in branding and to avoid potential module name conflicts

**Comment by txomin13** [comment]
I am also in favor of this renaming.

Regarding the math libraries, I am in favor of:

```
use hipblas -> use hipfort_hipblas 
```
vs.
```
use hipblas -> use hipfort_blas 
```

With the former variant, we can provide both an interface 
for hipblas and one for rocblas as done in PR #16.
