### ISSUE TITLE
Monthly HUG meeting proposal,  3rd Tuesday at 2PM EST. 

### ISSUE THREAD

**Issue by gregrodgers** [ROCmSoftwarePlatform/hipfort#25]
I would like to start a hipfort user group to manage the use, development, and release processes of hipfort.   How does the third Tuesday of the month at 2PM EST / 1PM CST / 11AM Pacific  sound?   I would serve as chairman for the first call.  However, I am looking for another leader to chair this group so that I can participate in other ways.   

I will hold an organizational  meeting Tuesday August 18 2PM-3PM EST to discuss.  The meeting will be on Microsoft Teams.  Send me email if you want an invitation.   Include any suggestions for HUG or hipfort. 

Greg Rodgers

**Comment by txomin13** [comment]
Time works for me. Did you send the invite out already?

**Comment by schoonovernumerics** [comment]
I don't think I got an invite for this - did this meeting happen today?

**Comment by gregrodgers** [comment]
Sorry, I am overwhelmed with deadlines. I did not get this arranged.

**Comment by cgmb** [comment]
I've taken over maintenance of hipfort and am starting by reviewing the open issues and PRs. I think this one can be closed out. hipfort has been adopted into the umbrella of the ROCm math and communication libraries, so the plan is to adopt their development and release processes. That covers 2/3rds of the topics that were mentioned.

Talking to users of hipfort remains important for understanding how they're using it and what they need from it. However, I'm not a big fan of meetings. I much prefer to be able to read and write about things asynchronously. It leaves more time to think and it creates a public record that can be reviewed and discussed by the broader userbase.

For the moment, it seems sufficient to use issues for bugs, feature requests, questions and all other user interactions related to the development of the library. @fluidnumerics-joe, if you have list of improvements you'd most like to see in hipfort, I'd be happy to review them.
