### ISSUE TITLE
vecadd does not compile on Nvidia hardware

### ISSUE THREAD

**Issue by schoonovernumerics** [ROCmSoftwarePlatform/hipfort#36]
**System Info**
Operating System : Ubuntu 20.04
GPU : Nvidia GTX 1070
CUDA Toolkit 11.0 installed
HIP Installed from ROCm 3.7.0

**Error message**
To recreate the error, update `test/vecadd/Makefile` so that `HIPFORT_HOME` points to hipfort installation path. Error only occurs on Nvidia hardware. After running make, the following output ensues :
```
/usr/bin/gfortran -cpp -I/opt/hipfort/include/nvptx "-DHIPFORT_ARCH=\"nvptx\""  -c main.f03 -o /home/joe/apps/hipfort/test/vecadd/main.o
HIP_PLATFORM=nvcc /opt/rocm/bin/hipcc "--gpu-architecture=sm_61" -c hip_implementation.cpp -o /home/joe/apps/hipfort/test/vecadd/hip_implementation.o
hip_implementation.cpp: In function ‘void vector_add(double*, double*, double*, int)’:
hip_implementation.cpp:6:18: error: ‘blockIdx’ was not declared in this scope
    6 |   size_t index = blockIdx.x * blockDim.x + threadIdx.x;
      |                  ^~~~~~~~
hip_implementation.cpp:6:31: error: ‘blockDim’ was not declared in this scope
    6 |   size_t index = blockIdx.x * blockDim.x + threadIdx.x;
      |                               ^~~~~~~~
hip_implementation.cpp:6:44: error: ‘threadIdx’ was not declared in this scope
    6 |   size_t index = blockIdx.x * blockDim.x + threadIdx.x;
      |                                            ^~~~~~~~~
hip_implementation.cpp:7:32: error: ‘gridDim’ was not declared in this scope
    7 |   size_t stride = blockDim.x * gridDim.x;
      |                                ^~~~~~~
In file included from /opt/rocm-3.7.0/hip/include/hip/hip_runtime.h:58,
                 from hip_implementation.cpp:1:
hip_implementation.cpp: In function ‘void launch(double**, double**, double**, int)’:
hip_implementation.cpp:19:5: error: expected primary-expression before ‘<’ token
   19 |     hipLaunchKernelGGL((vector_add), dim3(320), dim3(256), 0, 0, *dout, *da, *db, N);
      |     ^~~~~~~~~~~~~~~~~~
hip_implementation.cpp:19:5: error: expected primary-expression before ‘>’ token
   19 |     hipLaunchKernelGGL((vector_add), dim3(320), dim3(256), 0, 0, *dout, *da, *db, N);
      |     ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:19: /home/joe/apps/hipfort/test/vecadd/hip_implementation.o] Error 1
```

Outside of the undefined grid/thread/block errors, `hipcc` seems to now have compilation issues
```
hip_implementation.cpp:19:5: error: expected primary-expression before ‘<’ token
```

**Comment by txomin13** [comment]
There are three issues with this example:

1. `.cpp` is an extension that `nvcc` interprets as pure hostcode. We need to pass `-x cu` to force the correct behavior.
2. `hipcc` needs to know about the device architecture `nvcc` vs `hcc` to add the correct include directories.
3. `-cuopts` is not picked up by the `hipfc` wrapper script at the moment, i.e. we cannot pass `-x cu` manually.

On Volta (sm_70) the following recipes work:

```
export HIP_PLATFORM=nvcc
hipcc -c -x cu hip_implementation.cpp
hipfc --offload-arch sm_70 main.f03 hip_implementation.o -o main
```

The following injection hack works too:

```
export HIP_PLATFORM=nvcc

hipfc --offload-arch "sm_70 -x cu" main.f03 hip_implementation.cpp -o main # -cuda-path /usr/local/cuda-10.2 -rocm-dir /opt/rocm-3.7.0
```

We could:

1. Set `HIP_PLATFORM=nvcc` before calling hipcc if the offload arch is sm_xx.
2. Correctly implements the `-cuopts` option to enable passing `-x cu` to `nvcc`.
   Or always pass `-x cu` to `nvcc`?

**Comment by txomin13** [comment]
All tests compile and run successfully on NVIDIA hardware now with the latest main/master branch.
Ensure that you specify `--offload-arch=sm_XY` and add `-lcublas`, `-lcusolver`, or `-lcufft` where necessary.
