### ISSUE TITLE
add test/rocsolver/potrf.f03

### ISSUE THREAD

**Issue by yuhuibao** [ROCmSoftwarePlatform/hipfort#42]
use both hipfort_rocblas and hipfort_rocsolver causes 
call rocsolverCheck(rocsolver_dpotrf(rocsolver_handle,rocblas_fill_upper, N, B, ldb, c_loc(devInfo_d)))
Error: Name ‘rocblas_fill_upper’ at (1) is an ambiguous reference to ‘rocblas_fill_upper’ from module ‘hipfort_rocblas_enums’

**Comment by txomin13** [comment]
This issue is fixed on latest main/master.
