### ISSUE TITLE
MPI+ with HIPFort

### ISSUE THREAD

**Issue by fluidnumerics-joe** [ROCmSoftwarePlatform/hipfort#71]
Hey all, I wanted to reach out to discuss ideas on how to handle MPI+HIPFort . 
Ideally, I'd like to be able to pass GPU data (`c_ptr`) over MPI so that GPU direct communications can be used. 

However, it's looking like I'd have to duplicate the MPI code I have written in Fortran in C++ and provide another ISO_C_BINDING wrapper to call it from Fortran. While I've gotten to be ok with mixed language programming for writing GPU kernels, I'd prefer not to have to duplicate code to be able to use GPU direct communications.

Alternatively, I can go for a method of copying device pointers back to the host, handle MPI exchanges on the host, and copy back to GPU; for performance/scalability, this is less than ideal.

I'm interested in discussing with you all any alternative options, or if this kind of wrapper for MPI would be a good candidate for HIPFort.

**Comment by fluidnumerics-joe** [comment]
@domcharrier Without defining the interface block, how is the Fortran side made aware of the the routines defined in `.cpp` files ?

**Comment by domcharrier** [comment]
@fluidnumerics-joe  

> Without defining the interface block, how is the Fortran side made aware of the the routines defined in .cpp files ?

By default, Fortran compilers like gfortran will just assume that called subroutines or functions exist during compilation (as it can derive the signature (including return values) from the call site). 
Only at the linker stage, it will notice/know that a symbol is missing / present.

There are some switches to change this default behavior of gfortran:
```
-Wimplicit-interface        Warn about calls with implicit interface.
-Wimplicit-procedure        Warn about called procedures not explicitly declared.
```

> That's pretty clever. I'll give that a shot. If it works out, I can update the vecadd example, if this is the team's recommended strategy for working with HIP kernels in fortran

It is shorter but I wouldn't call it more clever as the Fortran compiler will assume how the interface
of the called function will look like and this assumption must be met by you, the C programmer, to prevent compilation and runtime issues.
It is not just the `<name>_`  that you need to tailor to the expectations of the Fortran compiler.
You further need to make sure that all arguments in your C function are pointer types, even
though you might pass a scalar on the Fortran side e.g.
With the explicit `interface ... end interface` declaration in Fortran, you overwrite assumptions of the Fortran compiler how the interface of a (C) procedure looks like.

GCC explains all this here:
https://gcc.gnu.org/onlinedocs/gfortran/Interoperability-with-C.html

Was quite an interesting resource for our latest Fortran project, which 
tries to generate HIP C++ kernels out of CUDA Fortran and OpenACC Fortran:
https://github.com/ROCmSoftwarePlatform/gpufort

**Comment by domcharrier** [comment]
@fluidnumerics-joe 

Regarding the interfaces on the Fortran side, check this out:

https://github.com/ROCmSoftwarePlatform/hipfort/commit/24fbd74e0f40c35519de9130163c7ecdd4e8aefa

Seems that C++ "&" can help to get rid of a lot of awkward pointer syntax on the C++ side.
