### ISSUE TITLE
Please enable two factor authentication in your github account

### ISSUE THREAD

**Issue by DeeptimayeeSethi** [ROCmSoftwarePlatform/hipfort#88]
@fluidnumerics-joe

We are going to enforce two factor authentication in (https://github.com/ROCmSoftwarePlatform/) organization on 29th April, 2022 . 
Since we identified you as outside collaborator for ROCmSoftwarePlatform organization, you need to enable two factor authentication in your github account else you shall be removed from the organization after the enforcement. 
Please skip if already done.

To set up two factor authentication, please go through the steps in below link:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication

Please email "Deeptimayee.Sethi@amd.com" for queries

**Comment by fluidnumerics-joe** [comment]
@DeeptimayeeSethi 2FA has been enabled for some time now on my account and thank you for the notice.

**Comment by DeeptimayeeSethi** [comment]
[AMD Official Use Only - General]

Hi Alex,

I can invite Natalia to the repo and not the organization as I see her email is not AMD but Gmail. Is she an AMDer or external collaborator?

Thanks,
Deepti

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alex-Cup** [comment]
Deepti, thank you for your reply.
Both Natalia and I are AMD vendor's employees (I, Oleksandr Kupriyanchuk, -
from Luxoft Ukraine; Natalia -- from Luxoft Russia, now its successor
company).
My email address is GMail as well. It seems that I am not even in any
organization: the "your organizations" line is even missing from my UI (see
the dropdown menu in the screenshot below).
Could you please invite Natalia, ***@***.*** (corporate:
***@***.***) and once again ***@***.***,
corporate: ***@***.***)? There can be two identities for me and
Natalia if needed.
Thank you,
Oleksandr




[image: image.png]








































































































































        -- these can be two identities) to the repo and if possible to the
organization.
[image: image.png]
